server:
  port: 8769

spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "123456"
  boot:
    admin:
      client:
        username: admin
        password: 123456

spring.boot.admin.client:
  username: admin
  password: 123456